// Even Fibonacci numbers
//        Problem 2
//        Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//        By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class Problem2 {
    public static String solve() {
        int sum = 0;
        int fibonacci1 = 1;
        int fibonacci2 = 2;

        while (fibonacci2 <= 4000000) {
            if (fibonacci2 % 2 == 0) {
                sum += fibonacci2;
            }

            int nextFibonacci = fibonacci1 + fibonacci2;
            fibonacci1 = fibonacci2;
            fibonacci2 = nextFibonacci;
        }

        return "The sum of all even valued Fibonacci numbers below four million is " + sum + ".";
    }
}
